### ISSUE TITLE
Errore: Chat not found

### ISSUE THREAD

**Issue by daxxxit** [paolofrancioso/telegrambot-amazon-bitly#4]
Ciao, sto provando ad eseguire lo script ma ottengo il seguente errore:

`Request received
Request received
Request received
INFO:root:***** Requests Completed *****
***** Creating post *****
INFO:root:***** Sending posts to channel *****
INFO:root:Chat not found`

Il TOKEN e il CHANNEL_NAME (con @) sono corretti, ho provati a riscriverli varie volte e anche a fare copia/incolla direttamente da botfather.
Anche quando provo l'invio manuale di un prodotto ottengo lo stesso errore:

`INFO:apscheduler.scheduler:Scheduler started
Message Received
Product Code: B09SG3VYW6
INFO:root:***** Requests Completed *****
***** Creating post *****
INFO:root:***** Sending post to channel *****
INFO:root:Chat not found`

Mi puoi aiutare?
Grazie

**Comment by daxxxit** [comment]
Ok guardando il codice ho risolto, o almeno così a me funziona....
In CHANNEL_NAME non va il nome del bot bensì il chat_id del bot, quindi:
CHANNEL_NAME = 'CHAT_ID_BOT'

**Comment by paolofrancioso** [comment]
Sì è il chat id. C'è un comando da lanciare comodo per ottenerlo come da Readme. Good luck!
