### ISSUE TITLE
Consigli

### ISSUE THREAD

**Issue by Alex87a** [paolofrancioso/telegrambot-amazon-bitly#6]
Salve Paolo, come va? Riscrivo qui dopo tantissimo tempo. In questi mesi non ho utilizzato più il Bot, ho avuto sempre paura che mi venisse restituito l'errore 429 Too Many Request. A tal proposito ti scrivo per capire se nel frattempo è stato ottimizzato ulteriormente il sistema delle chiamate. Se la risposta è negativo, volevo essenzialmente chiederti qualche tips per ridurre al minimo il rischio di comparsa dell'errore.
Grazie in anticipo.

**Comment by paolofrancioso** [comment]
Ciao Alex, rispondo tardissimo, ma solo per chiudere la Issue. Il tool è già abbastanza ottimizzato. L'ideale è estrarre non più di 2 richieste all'ora. Tieni presente che l'errore 429 spesso dipende dal numero di vendite che fai. Se vendi poco Amazon tende a limitare le tue chiamate, se sei un buon "referrer" invece sono un po' meno restrittivi. A me era capitato di avere un 429 su un canale "morto" e di riuscire con un'altra chiave a lavorare senza problemi. Non ho avuto particolari feedback in questi mesi, per cui suppongo che funzioni abbastanza bene. A presto!
